In [27]:
import torch
import torch.nn as nn

In [28]:
net=nn.Sequential(
    nn.Linear(3,2),
    nn.Softmax()
)

In [29]:
x=torch.randn(3,requires_grad=True)
print(x)

tensor([ 0.4330, -0.1891,  0.7897], requires_grad=True)


In [30]:
optimizer = torch.optim.Adam(net.parameters(), lr=1e-3)

In [36]:
print(net[0].weight.grad)
print(net[0].weight)
optimizer.zero_grad()
y=net(x)
print('y:',y)
loss=((1-y)**2).sum()
# net[0].weight.backward(torch.ones_like(net[0].weight))
print(net[0].weight.grad)
for i in range(3):
    net[0].weight.grad+=torch.rand_like(net[0].weight)# 自定义梯度
    print('grad:',net[0].weight.grad)
loss.backward()
optimizer.step()
print(net[0].weight)


tensor([[0.9857, 0.0036, 0.5893],
        [0.4053, 0.3110, 0.3381]])
Parameter containing:
tensor([[-0.0755, -0.4276, -0.1281],
        [-0.0323,  0.1614, -0.3018]], requires_grad=True)
y: tensor([0.7270, 0.2730], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
grad: tensor([[0.2307, 0.7215, 0.9777],
        [0.0976, 0.5627, 0.2673]])
grad: tensor([[1.0900, 0.9235, 1.2382],
        [0.3552, 0.8006, 1.0191]])
grad: tensor([[1.2397, 1.8754, 2.0516],
        [0.5247, 1.2256, 1.7160]])
Parameter containing:
tensor([[-0.0764, -0.4284, -0.1289],
        [-0.0330,  0.1607, -0.3026]], requires_grad=True)
